name: Install Production Release

on:
  workflow_dispatch:
    inputs:
      org-name:
        required: true
        type: string
        default: prod
      cumulusci-version:
        required: false
        type: string
      flow-name:
        required: true
        type: string

jobs:
    install-prod:
        uses: Nimba-Solutions/standard-workflows/.github/workflows/install-production.yml@main
        secrets:
          prod-org-auth-url: ${{ secrets.PROD_ORG_AUTH_URL }}
        with:
          cumulusci-version: "3.78.0"